#ifndef TESTSAMPLECODE_ACOONCLUSTERSHEURISTIC_H
#define TESTSAMPLECODE_ACOONCLUSTERSHEURISTIC_H
#include "ACOOnClusters.h"

void ACOOnClustersHeuristic();


#endif //TESTSAMPLECODE_ACOONCLUSTERSHEURISTIC_H
