//
// Created by wmw13 on 06/03/2021.
//

#ifndef TESTSAMPLECODE_CLKSEARCHHEURISTIC_H
#define TESTSAMPLECODE_CLKSEARCHHEURISTIC_H

#include "CLKSearch.h"
    void CLKSearchHeuristic();



#endif //TESTSAMPLECODE_CLKSEARCHHEURISTIC_H
