//
// Created by wmw13 on 05/02/2021.
//

#ifndef TESTSAMPLECODE_GREEDYEUCLIDEANHEURISTIC_H
#define TESTSAMPLECODE_GREEDYEUCLIDEANHEURISTIC_H

void greedyHeuristic(int,int);

#endif //TESTSAMPLECODE_GREEDYEUCLIDEANHEURISTIC_H
