//
// Created by wmw13 on 06/02/2021.
//

#ifndef TESTSAMPLECODE_DIJKSTRASHEURISTIC_H
#define TESTSAMPLECODE_DIJKSTRASHEURISTIC_H


void DijkstrasHeuristic();
int* Dijkstra();


#endif //TESTSAMPLECODE_DIJKSTRASHEURISTIC_H
